# Generated by Django 4.2.5 on 2023-11-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_country',
            new_name='country',
        ),
    ]
